Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -22,20 +22,20 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      - name: ごにょごにょ
+      - name: Collect mantela.schema.json from tags
         run: |
           # 出力用ディレクトリ
           mkdir ../build
           IFS=$'\n'
-          git tag | while read tag
+          git tag -l "v*" | while read tag
           do
-            #if [ -z "$line" ]; then continue; fi
             git checkout "$tag"
             if [ -e "mantela.schema.json" ]; then
               mkdir "../build/${tag}"
               cp mantela.schema.json "../build/${tag}/"
             else
-              echo "The file mantela.schema.json is not found in the tag ${tag}."
+              echo "The file mantela.schema.json is not found in the tag \"${tag}\"."
+              exit 1
             fi
           done
 
@@ -43,6 +43,9 @@ jobs:
           git checkout main
           if [ -e "mantela.schema.json" ]; then
             cp mantela.schema.json "../build/"
+          else
+            echo "The file mantela.schema.json is not found in the branch \"main\"."
+            exit 1
           fi
 
 
